In [1]:
print("Hello World")

Hello World


In [2]:
user = input("Enter your name:")
print(f"Welcome {user}.")

Welcome .


In [3]:
# def add(a,b):
#     return a+b

# num1 = int(input("Enter number:"))
# num2 = int(input("Enter number2:"))

# add(num1,num2)

In [4]:
# def check(n):
#     if n %2 == 0:
#         return f"Number {n} is even"
#     elif n %2 == 1:
#         return f"Number {n} is odd"
#     else:
#         return "Enter proper value"
    
# num1 = int(input("Enter number:"))
# check(num1)

In [5]:
def largest(x,y,z):
    if x > y and x > z:
        return f"Number {x} is largest"
    elif y > x and y > z:
        return f"Number {y} is largest"
    else:
        return f"Number {z} is largest"
    
largest(10,15,3)

'Number 15 is largest'

In [6]:
# Simple interest 
def simple(p,r,n):
    return (p*r*n)/(100)
simple(10000,5,2)

1000.0

In [7]:
#Print the multiplication table of a number.

def table(n):
    for i in range(1,11):
        ans = i*n
        print(f"{n} * {i} = {ans}")

table(2)

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [8]:
#Calculate the factorial of a number.'
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)
fact(5)

120

In [9]:
#Check if a number is prime.
def isprime(n):
    for i in range(n//2 -1):
        if n%2 == 0:
            return"Not prime"
        else:
            return "Prime"
        
isprime(20)

'Not prime'

In [10]:
#Print the Fibonacci series up to n terms.

def fibo(n):
    a ,b = 0,1
    next = b
    count =1
    while count <= n :
        print(next, end = " ")
        count += 1
        a,b = b,next
        next = a+b

fibo(10)

1 2 3 5 8 13 21 34 55 89 

In [11]:
def square_digits(num):
    digit = [int(d) for d in str(num)]
    res_list=[]
    for i in digit:
        i*=i
        res_list.append(i)
    number = int(''.join(str(d) for d in res_list))
    return number
    
square_digits(9119)

811181

In [12]:
# Create a Person class with attributes like name and age. Add a method to display their information.
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age 
    def display(self):
        return f"Welcome {self.name}, your age is {self.age}"
    
obj = Person('Nirav', 19)
obj.display()


'Welcome Nirav, your age is 19'

In [13]:
#Create a Student class that inherits from Person. Add attributes like roll_no and marks. Add a method to display full details.
class Student(Person):
    def __init__(self, name, age,roll_no,marks):
        super().__init__(name, age)
        self.marks= marks 
        self.roll_no = roll_no
    def display(self):
        return f"Hello {self.name},your age is {self.age}, roll_no is {self.roll_no} and marks are {self.marks}"
obj = Student('Nirav', 19,10,99)
obj.display()

'Hello Nirav,your age is 19, roll_no is 10 and marks are 99'

In [14]:
class Product:
    def __init__(self, name, price, quantity, category):
        self.name = name
        self.price = price
        self.quantity = quantity
        self.category = category

    def __str__(self):
        return f"Product: {self.name}, Price: ${self.price:.2f}, Quantity: {self.quantity}, Category: {self.category}"

class Category:
    def __init__(self, name):
        self.name = name
        self.products = []

    def add_product(self, product):
        self.products.append(product)

    def list_products(self):
        if not self.products:
            print("  No products in this category.")
        for product in self.products:
            print(f"  - {product}")

class InventoryManager:
    def __init__(self):
        self.inventory = {}

    def add_category(self, category_name):
        if category_name not in self.inventory:
            self.inventory[category_name] = Category(category_name)

    def add_product(self, name, price, quantity, category_name):
        self.add_category(category_name)  # Ensure category exists
        product = Product(name, price, quantity, category_name)
        self.inventory[category_name].add_product(product)

    def list_all_products(self):
        if not self.inventory:
            print("No categories in inventory.")
            return
        for category in self.inventory.values():
            print(f"\nCategory: {category.name}")
            category.list_products()

    def search_product(self, name):
        for category in self.inventory.values():
            for product in category.products:  # Corrected loop variable and access
                if product.name.lower() == name.lower():
                    return product
        return None

    def update_stock(self, product_name, quantity_change):
        product = self.search_product(product_name)
        if product:
            product.quantity += quantity_change
            return True
        return False

In [15]:
# Create an InventoryManager instance
manager = InventoryManager()

# Add some categories and products
manager.add_product("Laptop", 999.99, 10, "Electronics")
manager.add_product("Mouse", 29.99, 50, "Electronics")
manager.add_product("T-Shirt", 19.99, 100, "Clothing")

# List all products
manager.list_all_products()

# Search for a product
product = manager.search_product("laptop")
if product:
    print(f"\nFound: {product}")

# Update stock
if manager.update_stock("Laptop", -2):
    print("\nStock updated successfully.")
    manager.list_all_products()


Category: Electronics
  - Product: Laptop, Price: $999.99, Quantity: 10, Category: Electronics
  - Product: Mouse, Price: $29.99, Quantity: 50, Category: Electronics

Category: Clothing
  - Product: T-Shirt, Price: $19.99, Quantity: 100, Category: Clothing

Found: Product: Laptop, Price: $999.99, Quantity: 10, Category: Electronics

Stock updated successfully.

Category: Electronics
  - Product: Laptop, Price: $999.99, Quantity: 8, Category: Electronics
  - Product: Mouse, Price: $29.99, Quantity: 50, Category: Electronics

Category: Clothing
  - Product: T-Shirt, Price: $19.99, Quantity: 100, Category: Clothing


In [16]:
import numpy as np


In [17]:
ar1 = np.ones(5)
ar1

array([1., 1., 1., 1., 1.])

In [18]:
arr1  = np.zeros(5).astype(int)
arr1

array([0, 0, 0, 0, 0])

In [19]:
arr1 = np.zeros((3,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
arr1 = np.linspace(0,10,15)
arr1

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [21]:
arr1 = np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2],[3,4]])
arr1 = arr.flatten()
arr1

array([1, 2, 3, 4])

In [23]:
try:
    x = 10 /5
except Exception as e:
    print(e)
else:
    print(f'{x:.2f}')
finally:
    print("Excecution Completed ")

2.00
Excecution Completed 


In [24]:
arr = np.arange(1,10,dtype=int)
array = np.split(arr,3)
print(array)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [25]:
array  = np.arange(1,10,dtype=int).reshape(3,3)
# array.reshape(2,5)
print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
result = np.split(array, 3, axis=1)
result

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [27]:
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])
result = np.vsplit(matrix, 4)
result

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [28]:
# It will give the index where the element exits 
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
print("arr = {}".format(arr))
i = np.where(arr == 50)
print("i = {}".format(i))
arr.sort()
print(arr)

arr = [10 32 30 50 20 82 91 45]
i = (array([3]),)
[10 20 30 32 45 50 82 91]


In [29]:
print("Right most {}".format(np.searchsorted(arr,77,side='right')))


Right most 6


In [30]:
import pandas as pd

In [31]:
data  = [['vala', 20],['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data,columns=['Name','Age'])

In [32]:
df

Name  Age
0  vala   20
1   tom   10
2  nick   15
3  juli   14

In [35]:
data = [{'a':1,'b':2,'c':3},
        {'a':4,'b':5,'c':6}]
df = pd.DataFrame(data)
df

a  b  c
0  1  2  3
1  4  5  6

In [36]:
data = pd.DataFrame({
    'Name': ['Geek1', 'Geek2', 'Geek3', 'Geek4', 'Geek5'],
    'Age': [25, 30, 22, 35, 28],
    'Salary': [50000, 60000, 45000, 70000, 55000]
})

In [37]:
print("Original DataFrame:")
print(data)


Original DataFrame:
    Name  Age  Salary
0  Geek1   25   50000
1  Geek2   30   60000
2  Geek3   22   45000
3  Geek4   35   70000
4  Geek5   28   55000


In [46]:
df = data.iloc[0:]
print("Extracted row (geek1):")
print(df)

Extracted row (geek1):
    Name  Age  Salary
0  Geek1   25   50000
1  Geek2   30   60000
2  Geek3   22   45000
3  Geek4   35   70000
4  Geek5   28   55000


In [44]:

first = data["Name"]
second = data["Age"]

print(data.loc[0:1])
# print(first, "\n\n\n", second)

    Name  Age  Salary
0  Geek1   25   50000
1  Geek2   30   60000


In [47]:
df.loc[len(df)]= ['Geek1',25,90000]
print(df)

    Name  Age  Salary
0  Geek1   25   50000
1  Geek2   30   60000
2  Geek3   22   45000
3  Geek4   35   70000
4  Geek5   28   55000
5  Geek1   25   90000


C:\Users\Nirav\AppData\Local\Temp\ipykernel_19696\3170623957.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[len(df)]= ['Geek1',25,90000]


In [51]:
name = input("Enter the name")
df1 = df.apply(lambda x : x if x['Name'] == name else None, axis =1 )
df1 = df1.dropna().reset_index(drop=True)
print(df1)

    Name   Age   Salary
0  Geek1  25.0  50000.0
1  Geek1  25.0  90000.0


In [52]:
df1 = df[df['Name'] == name]
print(df1)

    Name  Age  Salary
0  Geek1   25   50000
5  Geek1   25   90000
